services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cosmix-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cosmix-net

  db:
    image: postgres:16
    container_name: cosmix-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infrastructure/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cosmix-net

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cosmix-cloudbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"
    volumes:
      - cloudbeaver-data:/opt/cloudbeaver/workspace
    depends_on:
      - db
    networks:
      - cosmix-net

  mailpit:
    image: axllent/mailpit:latest
    container_name: cosmix-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailpit-data:/data
    environment:
      MP_DATABASE: /data/mailpit.db
    networks:
      - cosmix-net

networks:
  cosmix-net:

volumes:
  pgdata:
  mailpit-data:
  cloudbeaver-data: